# Generated by Django 3.1.3 on 2020-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('M/F', 'M/F')], max_length=3)),
                ('interests', models.CharField(max_length=200)),
                ('bio_message', models.TextField()),
            ],
        ),
    ]
