# Generated by Django 3.1.3 on 2020-12-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
